package org.example.task6;

import java.io.*;
import java.util.*;
import java.util.concurrent.Callable;

public class MyCallableClass implements Callable {

    @Override
    public List<String> call() throws Exception {

        List<String> filesNameList = new ArrayList<>();
        List<File> filesList = new ArrayList<>();
        Random random = new Random();

        for (int i = 0; i < 10; i++) {
            String fileName = "/Users/rail/IdeaProjects/Java/SkillSpace_Java-Core/test/File_" + i + ".txt";
            File file = new File(fileName);
            file.createNewFile();

            try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(file))) {
                String[] randomWordsArr = {" as well as you do", " like you", " like he does", ", but I also like SQL",
                        " and it is super", " and it is my life", " but it isn't easy"};
                String text = "I love java" + randomWordsArr[random.nextInt(7)];
                bufferedWriter.write(text);
            }
            filesList.add(file);
        }
        int randomTime = random.nextInt(3);
        Thread.sleep(randomTime * 1000);

        for (File getFileName : filesList) {
            String fileName = getFileName.getName();
            filesNameList.add(fileName);
            System.out.println("Generated file is: " + fileName + " generated by: "
                    + Thread.currentThread().getName());
        }

        return filesNameList;
    }

}
