package org.example.task8;

import java.io.*;
import java.time.LocalDateTime;
import java.util.Locale;
import java.util.Scanner;
import java.util.concurrent.Callable;

public class MyTimer implements Callable {

    private LocalDateTime localDateTime = LocalDateTime.now();
    private final Object lock = new Object();
    private String text = "Hello world ";


    @Override
    public String call() throws Exception {
        String fileName = "/Users/rail/IdeaProjects/Java/SkillSpace_Java-Core/test/Date_File_.txt";
        File file = new File(fileName);
        Scanner sc = new Scanner(file);
        file.createNewFile();

        synchronized (lock) {
            try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(file))) {
                bufferedWriter.write(text + localDateTime);
            }
        }

        String line = sc.nextLine();
        System.out.println(line + " generated by: " + Thread.currentThread().getName());

        return line;
    }
}
