package org.example.task7;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.Callable;

public class NumberGenerator implements Callable {

    @Override
    public String call() throws Exception {
        Random random = new Random();
        List<Integer> numberList = new ArrayList<>();

        for (int i = 0; i < 10; i++) {
            numberList.add(random.nextInt(100));
        }
        Integer sum = 0;

        for (Integer integer : numberList) {
            sum = integer + sum;
        }

        int randomTime = random.nextInt(10);
        Thread.sleep(randomTime * 1000);
        String result = sum.toString();
        System.out.println("Result is: " + result + " generated by: " + Thread.currentThread().getName());

        return result;
    }

}
